---
title: "Projekt 1"
output: github_document
---

## Analiza skryptów i plików .R z pakietów

Projekt przygotowany na przedmiot *R dla zaawansowanych* na Politechnice Warszawskiej,
na Wydziale Matematyki i Nauk Informacyjnych przez
Elizę Kaczorek,
Małgosię Łazęcką,
Kasię Woźnicę.

## Zawartość:

1. pliki do scrapowania danych z Githuba i CRANA:

    * CRAN_webscraping.R
    * Github_webscraping.R

2. plik do wyciągania nazw funkcji, zmiennych i pakietów
   z pojedynczego skryptu:

    * Wyciaganie_informacji.R

3. plik do tworzenia plików .txt z podsumowaniem dla każdego autora osobno:

    * Summary_git_cran.R

4. plik do tworzenia tabel z ogólnym podsumowaniem:

    * Tworzenie_tabel_do_analizy.R

5. tabele - wynik działania poprzedniego:
 
    * LISTA_TABEL.rda

6. plik do tworzenia raporu:

    * RaportWyniki.Rmd

7. przygotowany przez nas raport:

    * RaportWyniki.html
   
### Jeśli chcesz odtworzyć wyniki zaczynając od ściągniętych pakietów:

  Pliki .R znajdują się pod linkiem:

  https://drive.google.com/drive/folders/1pli8ri_Y_zXmnLcpx8NGJKSFfcV5MIoz?usp=sharing

  Są tam zarówno pliki z Githuba, jak i z CRANa, jednak ich nazwy się różnią.
  
* Pliki z Githuba: grupa_autor_nazwaplikuRowego
* Pliki z CRANa: grupa_nazwapakietu_nazwaplikuRowego
  
  Aby pomóc w poruszaniu się po plikach zamieściłyśmy dodatkowe pliki z podsumowaniem.

### Jeśli chcesz odtworzyć wyniki zaczynając od tabel:

  Skorzystaj z LISTA_TABEL.rda
  
  Zawiera ona 6 tabel - pierwsze 3 dotyczą grupy A, ostatnie 3 grupy B. Każda z 3 zawiera nazwy funkcji, zmiennych i pakietów.

### Dodatkowe informacje:

* Grupa A - skrypty z pakietów
* Grupa B - skrypty do analiz